export const adminEmailTemplate = (data) => {
  const { name, email, phone, orderNumber, subject, message } = data;
  return `
    <div style="font-family: Arial, sans-serif; background-color: #0f172a; color: #f8fafc; padding: 25px; border-radius: 10px; max-width: 600px; margin: 0 auto; border: 1px solid #febd69;">
      <h2 style="color: #febd69; border-bottom: 2px solid #febd69; padding-bottom: 10px; margin-top: 0;">
        📩 New Contact Inquiry - NexCart
      </h2>
      <p style="font-size: 15px; color: #cbd5e1;">You have received a new contact form submission from a customer:</p>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 15px; background-color: #1e293b; border-radius: 8px; overflow: hidden;">
        <tr>
          <td style="padding: 12px; font-weight: bold; color: #febd69; border-bottom: 1px solid #334155; width: 35%;">Customer Name:</td>
          <td style="padding: 12px; color: #ffffff; border-bottom: 1px solid #334155;">${name}</td>
        </tr>
        <tr>
          <td style="padding: 12px; font-weight: bold; color: #febd69; border-bottom: 1px solid #334155;">Email Address:</td>
          <td style="padding: 12px; color: #ffffff; border-bottom: 1px solid #334155;">${email}</td>
        </tr>
        <tr>
          <td style="padding: 12px; font-weight: bold; color: #febd69; border-bottom: 1px solid #334155;">Phone Number:</td>
          <td style="padding: 12px; color: #ffffff; border-bottom: 1px solid #334155;">${phone || "N/A"}</td>
        </tr>
        <tr>
          <td style="padding: 12px; font-weight: bold; color: #febd69; border-bottom: 1px solid #334155;">Order ID / Number:</td>
          <td style="padding: 12px; color: #ffffff; border-bottom: 1px solid #334155;">${orderNumber || "N/A"}</td>
        </tr>
        <tr>
          <td style="padding: 12px; font-weight: bold; color: #febd69; border-bottom: 1px solid #334155;">Subject / Topic:</td>
          <td style="padding: 12px; color: #ffffff; border-bottom: 1px solid #334155;">${subject || "General Inquiry"}</td>
        </tr>
        <tr>
          <td style="padding: 12px; font-weight: bold; color: #febd69; vertical-align: top;">Message:</td>
          <td style="padding: 12px; color: #ffffff; line-height: 1.6;">${message}</td>
        </tr>
      </table>

      <div style="margin-top: 25px; padding-top: 15px; border-top: 1px solid #334155; font-size: 12px; color: #94a3b8; text-align: center;">
        This email was automatically generated by <strong>NexCart Customer Support System</strong>.
      </div>
    </div>
  `;
};

export const userEmailTemplate = (data) => {
  const { name, subject } = data;
  return `
    <div style="font-family: Arial, sans-serif; background-color: #0f172a; color: #f8fafc; padding: 25px; border-radius: 10px; max-width: 600px; margin: 0 auto; border: 1px solid #febd69;">
      <div style="text-align: center; margin-bottom: 20px;">
        <h1 style="color: #febd69; margin: 0; font-size: 26px;">NexCart Support</h1>
        <p style="color: #94a3b8; font-size: 14px; margin-top: 5px;">Thank you for getting in touch with us!</p>
      </div>

      <p style="font-size: 16px; color: #ffffff;">Hello <strong>${name}</strong>,</p>

      <p style="font-size: 15px; color: #cbd5e1; line-height: 1.6;">
        Thank you for contacting <strong>NexCart</strong>. We have successfully received your inquiry regarding 
        <span style="color: #febd69; font-weight: bold;">"${subject || "General Inquiry"}"</span>.
      </p>

      <div style="background-color: #1e293b; padding: 18px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #febd69;">
        <p style="margin: 0; color: #e2e8f0; font-size: 14px; line-height: 1.5;">
          ⏱️ <strong>What happens next?</strong><br/>
          Our support team is reviewing your message and will respond to you via this email within <strong>24 business hours</strong>.
        </p>
      </div>

      <p style="font-size: 14px; color: #cbd5e1;">
        If you have urgent details to add, feel free to reply directly to this email.
      </p>

      <div style="margin-top: 30px; padding-top: 15px; border-top: 1px solid #334155; text-align: center;">
        <p style="font-size: 14px; color: #febd69; font-weight: bold; margin-bottom: 5px;">Happy Shopping!</p>
        <p style="font-size: 12px; color: #64748b; margin: 0;">NexCart E-Commerce Team &bull; www.nexcart.com</p>
      </div>
    </div>
  `;
};
